//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCorruptionSeachEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class link_website_words
    {
        public int id { get; set; }
        public Nullable<int> rank { get; set; }
        public Nullable<int> website_id { get; set; }
        public Nullable<int> word_id { get; set; }
    
        public virtual website website { get; set; }
        public virtual word word { get; set; }
    }
}
