//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCorruptionSeachEngine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SearchEntities : DbContext
    {
        public SearchEntities()
            : base("name=SearchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_users> admin_users { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<did_you_know> did_you_know { get; set; }
        public virtual DbSet<history> histories { get; set; }
        public virtual DbSet<industry> industries { get; set; }
        public virtual DbSet<link_country_website> link_country_website { get; set; }
        public virtual DbSet<link_industry_website> link_industry_website { get; set; }
        public virtual DbSet<link_website_words> link_website_words { get; set; }
        public virtual DbSet<website> websites { get; set; }
        public virtual DbSet<word> words { get; set; }
    }
}
