//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCorruptionSeachEngine
{
    using System;
    using System.Collections.Generic;
    
    public partial class word
    {
        public word()
        {
            this.link_website_words = new HashSet<link_website_words>();
        }
    
        public int id { get; set; }
        public string phrase { get; set; }
    
        public virtual ICollection<link_website_words> link_website_words { get; set; }
    }
}
